version: "3"
services:

  gateway:
    image: nginx:1.25-bookworm
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-service
      - payment-service

  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
    volumes:
      - ./logging:/home/flask-app/logging
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=debug -c gunicorn_config.py app:app
    env_file:
      - env/order_redis.env
    depends_on:
      - order-db
      - kafka

  order-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  stock-service:
    build: ./stock
    image: stock:latest
    volumes:
      - ./logging:/home/flask-app/logging
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=debug -c gunicorn_config.py app:app
    env_file:
      - env/stock_redis.env
    depends_on:
      - stock-db
      - kafka

  stock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-service:
    build: ./payment
    image: user:latest
    volumes:
      - ./logging:/home/flask-app/logging
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=debug -c gunicorn_config.py app:app
    env_file:
      - env/payment_redis.env
    depends_on:
      - payment-db
      - kafka

  payment-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk 
    volumes:
      - ./kafka:/bitnami/kafka
