# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/payment.proto\x1a\x1cgoogle/protobuf/struct.proto\"8\n\x13\x42\x61tchInitPayRequest\x12\t\n\x01n\x18\x01 \x01(\x05\x12\x16\n\x0estarting_money\x18\x02 \x01(\x05\"\'\n\x14\x42\x61tchInitPayResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x13\n\x11\x43reateUserRequest\"%\n\x12\x43reateUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\"\n\x0f\x46indUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"3\n\x10\x46indUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63redit\x18\x02 \x01(\x05\"/\n\x0c\x46undsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"4\n\rFundsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nstatuscode\x18\x02 \x01(\x05\x32\xd1\x02\n\x0ePaymentService\x12\x37\n\x08get_json\x12\x12.CreateUserRequest\x1a\x17.google.protobuf.Struct\x12?\n\x10\x62\x61tch_init_users\x12\x14.BatchInitPayRequest\x1a\x15.BatchInitPayResponse\x12\x36\n\x0b\x63reate_user\x12\x12.CreateUserRequest\x1a\x13.CreateUserResponse\x12\x30\n\tfind_user\x12\x10.FindUserRequest\x1a\x11.FindUserResponse\x12+\n\nadd_credit\x12\r.FundsRequest\x1a\x0e.FundsResponse\x12.\n\rremove_credit\x12\r.FundsRequest\x1a\x0e.FundsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATCHINITPAYREQUEST']._serialized_start=54
  _globals['_BATCHINITPAYREQUEST']._serialized_end=110
  _globals['_BATCHINITPAYRESPONSE']._serialized_start=112
  _globals['_BATCHINITPAYRESPONSE']._serialized_end=151
  _globals['_CREATEUSERREQUEST']._serialized_start=153
  _globals['_CREATEUSERREQUEST']._serialized_end=172
  _globals['_CREATEUSERRESPONSE']._serialized_start=174
  _globals['_CREATEUSERRESPONSE']._serialized_end=211
  _globals['_FINDUSERREQUEST']._serialized_start=213
  _globals['_FINDUSERREQUEST']._serialized_end=247
  _globals['_FINDUSERRESPONSE']._serialized_start=249
  _globals['_FINDUSERRESPONSE']._serialized_end=300
  _globals['_FUNDSREQUEST']._serialized_start=302
  _globals['_FUNDSREQUEST']._serialized_end=349
  _globals['_FUNDSRESPONSE']._serialized_start=351
  _globals['_FUNDSRESPONSE']._serialized_end=403
  _globals['_PAYMENTSERVICE']._serialized_start=406
  _globals['_PAYMENTSERVICE']._serialized_end=743
# @@protoc_insertion_point(module_scope)
