# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stock.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstock.proto\"I\n\x10\x42\x61tchInitRequest\x12\t\n\x01n\x18\x01 \x01(\x05\x12\x16\n\x0estarting_money\x18\x02 \x01(\x05\x12\x12\n\nitem_price\x18\x03 \x01(\x05\"$\n\x11\x42\x61tchInitResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x11\x43reateItemRequest\x12\r\n\x05price\x18\x01 \x01(\x05\"%\n\x12\x43reateItemResponse\x12\x0f\n\x07item_id\x18\x01 \x01(\t\"\"\n\x0f\x46indItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\"0\n\x10\x46indItemResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\x12\r\n\x05price\x18\x02 \x01(\x05\"/\n\x0cStockRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"#\n\rStockResponse\x12\x12\n\nstatuscode\x18\x01 \x01(\x05\x32\x8e\x02\n\x0cStockService\x12\x39\n\x10\x62\x61tch_init_users\x12\x11.BatchInitRequest\x1a\x12.BatchInitResponse\x12\x36\n\x0b\x63reate_item\x12\x12.CreateItemRequest\x1a\x13.CreateItemResponse\x12\x30\n\tfind_item\x12\x10.FindItemRequest\x1a\x11.FindItemResponse\x12*\n\tadd_stock\x12\r.StockRequest\x1a\x0e.StockResponse\x12-\n\x0cremove_stock\x12\r.StockRequest\x1a\x0e.StockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATCHINITREQUEST']._serialized_start=15
  _globals['_BATCHINITREQUEST']._serialized_end=88
  _globals['_BATCHINITRESPONSE']._serialized_start=90
  _globals['_BATCHINITRESPONSE']._serialized_end=126
  _globals['_CREATEITEMREQUEST']._serialized_start=128
  _globals['_CREATEITEMREQUEST']._serialized_end=162
  _globals['_CREATEITEMRESPONSE']._serialized_start=164
  _globals['_CREATEITEMRESPONSE']._serialized_end=201
  _globals['_FINDITEMREQUEST']._serialized_start=203
  _globals['_FINDITEMREQUEST']._serialized_end=237
  _globals['_FINDITEMRESPONSE']._serialized_start=239
  _globals['_FINDITEMRESPONSE']._serialized_end=287
  _globals['_STOCKREQUEST']._serialized_start=289
  _globals['_STOCKREQUEST']._serialized_end=336
  _globals['_STOCKRESPONSE']._serialized_start=338
  _globals['_STOCKRESPONSE']._serialized_end=373
  _globals['_STOCKSERVICE']._serialized_start=376
  _globals['_STOCKSERVICE']._serialized_end=646
# @@protoc_insertion_point(module_scope)
