# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/stock.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/stock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/stock.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x0f\n\rEmptySRequest\"N\n\x15\x42\x61tchInitStockRequest\x12\t\n\x01n\x18\x01 \x01(\x05\x12\x16\n\x0estarting_money\x18\x02 \x01(\x05\x12\x12\n\nitem_price\x18\x03 \x01(\x05\")\n\x16\x42\x61tchInitStockResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x11\x43reateItemRequest\x12\r\n\x05price\x18\x01 \x01(\x05\"%\n\x12\x43reateItemResponse\x12\x0f\n\x07item_id\x18\x01 \x01(\t\"\"\n\x0f\x46indItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\"0\n\x10\x46indItemResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\x12\r\n\x05price\x18\x02 \x01(\x05\"/\n\x0cStockRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"4\n\rStockResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nstatuscode\x18\x02 \x01(\x05\x32\xcd\x02\n\x0cStockService\x12\x33\n\x08get_json\x12\x0e.EmptySRequest\x1a\x17.google.protobuf.Struct\x12\x43\n\x10\x62\x61tch_init_users\x12\x16.BatchInitStockRequest\x1a\x17.BatchInitStockResponse\x12\x36\n\x0b\x63reate_item\x12\x12.CreateItemRequest\x1a\x13.CreateItemResponse\x12\x30\n\tfind_item\x12\x10.FindItemRequest\x1a\x11.FindItemResponse\x12*\n\tadd_stock\x12\r.StockRequest\x1a\x0e.StockResponse\x12-\n\x0cremove_stock\x12\r.StockRequest\x1a\x0e.StockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.stock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYSREQUEST']._serialized_start=52
  _globals['_EMPTYSREQUEST']._serialized_end=67
  _globals['_BATCHINITSTOCKREQUEST']._serialized_start=69
  _globals['_BATCHINITSTOCKREQUEST']._serialized_end=147
  _globals['_BATCHINITSTOCKRESPONSE']._serialized_start=149
  _globals['_BATCHINITSTOCKRESPONSE']._serialized_end=190
  _globals['_CREATEITEMREQUEST']._serialized_start=192
  _globals['_CREATEITEMREQUEST']._serialized_end=226
  _globals['_CREATEITEMRESPONSE']._serialized_start=228
  _globals['_CREATEITEMRESPONSE']._serialized_end=265
  _globals['_FINDITEMREQUEST']._serialized_start=267
  _globals['_FINDITEMREQUEST']._serialized_end=301
  _globals['_FINDITEMRESPONSE']._serialized_start=303
  _globals['_FINDITEMRESPONSE']._serialized_end=351
  _globals['_STOCKREQUEST']._serialized_start=353
  _globals['_STOCKREQUEST']._serialized_end=400
  _globals['_STOCKRESPONSE']._serialized_start=402
  _globals['_STOCKRESPONSE']._serialized_end=454
  _globals['_STOCKSERVICE']._serialized_start=457
  _globals['_STOCKSERVICE']._serialized_end=790
# @@protoc_insertion_point(module_scope)
