# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from protos import order_pb2 as protos_dot_order__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/order_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_json = channel.unary_unary(
                '/OrderService/get_json',
                request_serializer=protos_dot_order__pb2.EmptyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
                _registered_method=True)
        self.batch_init_users = channel.unary_unary(
                '/OrderService/batch_init_users',
                request_serializer=protos_dot_order__pb2.BatchInitOrderRequest.SerializeToString,
                response_deserializer=protos_dot_order__pb2.BatchInitOrderResponse.FromString,
                _registered_method=True)
        self.create_order = channel.unary_unary(
                '/OrderService/create_order',
                request_serializer=protos_dot_order__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=protos_dot_order__pb2.CreateOrderResponse.FromString,
                _registered_method=True)
        self.find_order = channel.unary_unary(
                '/OrderService/find_order',
                request_serializer=protos_dot_order__pb2.OrderIdRequest.SerializeToString,
                response_deserializer=protos_dot_order__pb2.FindOrderResponse.FromString,
                _registered_method=True)
        self.add_item = channel.unary_unary(
                '/OrderService/add_item',
                request_serializer=protos_dot_order__pb2.AddItemRequest.SerializeToString,
                response_deserializer=protos_dot_order__pb2.StatuscodeResponse.FromString,
                _registered_method=True)
        self.checkout = channel.unary_unary(
                '/OrderService/checkout',
                request_serializer=protos_dot_order__pb2.OrderIdRequest.SerializeToString,
                response_deserializer=protos_dot_order__pb2.StatuscodeResponse.FromString,
                _registered_method=True)


class OrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_json(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def batch_init_users(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_order(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def find_order(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_item(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_json': grpc.unary_unary_rpc_method_handler(
                    servicer.get_json,
                    request_deserializer=protos_dot_order__pb2.EmptyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
            ),
            'batch_init_users': grpc.unary_unary_rpc_method_handler(
                    servicer.batch_init_users,
                    request_deserializer=protos_dot_order__pb2.BatchInitOrderRequest.FromString,
                    response_serializer=protos_dot_order__pb2.BatchInitOrderResponse.SerializeToString,
            ),
            'create_order': grpc.unary_unary_rpc_method_handler(
                    servicer.create_order,
                    request_deserializer=protos_dot_order__pb2.CreateOrderRequest.FromString,
                    response_serializer=protos_dot_order__pb2.CreateOrderResponse.SerializeToString,
            ),
            'find_order': grpc.unary_unary_rpc_method_handler(
                    servicer.find_order,
                    request_deserializer=protos_dot_order__pb2.OrderIdRequest.FromString,
                    response_serializer=protos_dot_order__pb2.FindOrderResponse.SerializeToString,
            ),
            'add_item': grpc.unary_unary_rpc_method_handler(
                    servicer.add_item,
                    request_deserializer=protos_dot_order__pb2.AddItemRequest.FromString,
                    response_serializer=protos_dot_order__pb2.StatuscodeResponse.SerializeToString,
            ),
            'checkout': grpc.unary_unary_rpc_method_handler(
                    servicer.checkout,
                    request_deserializer=protos_dot_order__pb2.OrderIdRequest.FromString,
                    response_serializer=protos_dot_order__pb2.StatuscodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('OrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_json(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderService/get_json',
            protos_dot_order__pb2.EmptyRequest.SerializeToString,
            google_dot_protobuf_dot_struct__pb2.Struct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def batch_init_users(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderService/batch_init_users',
            protos_dot_order__pb2.BatchInitOrderRequest.SerializeToString,
            protos_dot_order__pb2.BatchInitOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_order(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderService/create_order',
            protos_dot_order__pb2.CreateOrderRequest.SerializeToString,
            protos_dot_order__pb2.CreateOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def find_order(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderService/find_order',
            protos_dot_order__pb2.OrderIdRequest.SerializeToString,
            protos_dot_order__pb2.FindOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_item(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderService/add_item',
            protos_dot_order__pb2.AddItemRequest.SerializeToString,
            protos_dot_order__pb2.StatuscodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def checkout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderService/checkout',
            protos_dot_order__pb2.OrderIdRequest.SerializeToString,
            protos_dot_order__pb2.StatuscodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
