# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/order.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/order.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x0e\n\x0c\x45mptyRequest\"X\n\x15\x42\x61tchInitOrderRequest\x12\t\n\x01n\x18\x01 \x01(\x05\x12\x0f\n\x07n_items\x18\x02 \x01(\x05\x12\x0f\n\x07n_users\x18\x03 \x01(\x05\x12\x12\n\nitem_price\x18\x04 \x01(\x05\")\n\x16\x42\x61tchInitOrderResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x12\x43reateOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\'\n\x13\x43reateOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\"\n\x0eOrderIdRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"g\n\x11\x46indOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0c\n\x04paid\x18\x02 \x01(\x08\x12\r\n\x05items\x18\x03 \x03(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x12\n\ntotal_cost\x18\x05 \x01(\x05\"E\n\x0e\x41\x64\x64ItemRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"9\n\x12StatuscodeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nstatuscode\x18\x02 \x01(\x05\x32\xd9\x02\n\x0cOrderService\x12\x32\n\x08get_json\x12\r.EmptyRequest\x1a\x17.google.protobuf.Struct\x12\x43\n\x10\x62\x61tch_init_users\x12\x16.BatchInitOrderRequest\x1a\x17.BatchInitOrderResponse\x12\x39\n\x0c\x63reate_order\x12\x13.CreateOrderRequest\x1a\x14.CreateOrderResponse\x12\x31\n\nfind_order\x12\x0f.OrderIdRequest\x1a\x12.FindOrderResponse\x12\x30\n\x08\x61\x64\x64_item\x12\x0f.AddItemRequest\x1a\x13.StatuscodeResponse\x12\x30\n\x08\x63heckout\x12\x0f.OrderIdRequest\x1a\x13.StatuscodeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=52
  _globals['_EMPTYREQUEST']._serialized_end=66
  _globals['_BATCHINITORDERREQUEST']._serialized_start=68
  _globals['_BATCHINITORDERREQUEST']._serialized_end=156
  _globals['_BATCHINITORDERRESPONSE']._serialized_start=158
  _globals['_BATCHINITORDERRESPONSE']._serialized_end=199
  _globals['_CREATEORDERREQUEST']._serialized_start=201
  _globals['_CREATEORDERREQUEST']._serialized_end=238
  _globals['_CREATEORDERRESPONSE']._serialized_start=240
  _globals['_CREATEORDERRESPONSE']._serialized_end=279
  _globals['_ORDERIDREQUEST']._serialized_start=281
  _globals['_ORDERIDREQUEST']._serialized_end=315
  _globals['_FINDORDERRESPONSE']._serialized_start=317
  _globals['_FINDORDERRESPONSE']._serialized_end=420
  _globals['_ADDITEMREQUEST']._serialized_start=422
  _globals['_ADDITEMREQUEST']._serialized_end=491
  _globals['_STATUSCODERESPONSE']._serialized_start=493
  _globals['_STATUSCODERESPONSE']._serialized_end=550
  _globals['_ORDERSERVICE']._serialized_start=553
  _globals['_ORDERSERVICE']._serialized_end=898
# @@protoc_insertion_point(module_scope)
