# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\"5\n\x10\x42\x61tchInitRequest\x12\t\n\x01n\x18\x01 \x01(\x05\x12\x16\n\x0estarting_money\x18\x02 \x01(\x05\"$\n\x11\x42\x61tchInitResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x13\n\x11\x43reateUserRequest\"%\n\x12\x43reateUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\"\n\x0f\x46indUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"3\n\x10\x46indUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63redit\x18\x02 \x01(\x05\"/\n\x0c\x46undsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"#\n\rFundsResponse\x12\x12\n\nstatuscode\x18\x01 \x01(\x05\x32\x90\x02\n\x0ePaymentService\x12\x39\n\x10\x62\x61tch_init_users\x12\x11.BatchInitRequest\x1a\x12.BatchInitResponse\x12\x36\n\x0b\x63reate_user\x12\x12.CreateUserRequest\x1a\x13.CreateUserResponse\x12\x30\n\tfind_user\x12\x10.FindUserRequest\x1a\x11.FindUserResponse\x12*\n\tadd_funds\x12\r.FundsRequest\x1a\x0e.FundsResponse\x12-\n\x0cremove_funds\x12\r.FundsRequest\x1a\x0e.FundsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATCHINITREQUEST']._serialized_start=17
  _globals['_BATCHINITREQUEST']._serialized_end=70
  _globals['_BATCHINITRESPONSE']._serialized_start=72
  _globals['_BATCHINITRESPONSE']._serialized_end=108
  _globals['_CREATEUSERREQUEST']._serialized_start=110
  _globals['_CREATEUSERREQUEST']._serialized_end=129
  _globals['_CREATEUSERRESPONSE']._serialized_start=131
  _globals['_CREATEUSERRESPONSE']._serialized_end=168
  _globals['_FINDUSERREQUEST']._serialized_start=170
  _globals['_FINDUSERREQUEST']._serialized_end=204
  _globals['_FINDUSERRESPONSE']._serialized_start=206
  _globals['_FINDUSERRESPONSE']._serialized_end=257
  _globals['_FUNDSREQUEST']._serialized_start=259
  _globals['_FUNDSREQUEST']._serialized_end=306
  _globals['_FUNDSRESPONSE']._serialized_start=308
  _globals['_FUNDSRESPONSE']._serialized_end=343
  _globals['_PAYMENTSERVICE']._serialized_start=346
  _globals['_PAYMENTSERVICE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
